name: Publish prod image
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build main branch
    permissions: write-all
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t nuit-info-website-docker .

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nuit-info-2024/website/main
          tags: latest

#      - name: SSH into server and redeploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            docker compose -f ./dailycanvas/docker-compose.yml pull
#            docker compose -f ./dailycanvas/docker-compose.yml up -d
